---
title: "Call for Abstracts"
date: "2023-10-31"
published-title: "Due date:"
---

We sincerely invite you to submit abstracts to the International Conference on Bio-mediated and Bio-inspired Geotechnics (ICBBG) 2025, scheduled to take place in Temple, Arizona, USA from May 19^th^ to 21^st^, 2023. 
ICBBG aims to bring together top researchers from around the world to present the state of the art and state of the practice on biogeotechnics, and to facilitate knowledge exchange among researchers, industry, agencies and educators.

## Themes

We call for submissions to 8 general sessions and 8 special symposia:

```{r} 
library(kableExtra)
library(tidyverse)

themes <- tribble(
  ~"General sessions", ~"Special symposia",
"Bio-mediated methods for hazard mitigation                        ", "Bio-inspired Tunneling                         ",
"Bio-mediated methods for environmental protection and restoration ", "Asia experiences on bio-mediated geotechnics   ",
"Bio-mediated methods for infrastructure construction              ", "Europe experiences on bio-mediated geotechnics ",
"Bio-inspired methods for infrastructure construction              ", "Biopolymer treated soils                       ",
"Bio-inspired methods for subsurface exploration and excavation    ", "Delivery strategies for MICP                   ",
"Fundamental research on biogeotechnics                            ", "MICP for sustainable geoenergy applications    ",
"Case studies on field applications of biogeotechnics              ", "Fungal treatment of soils                      ",
"Education and outreach in biogeotechnics                          ", "Build with nature                              ",
) 
kbl(themes) %>%
  column_spec(1, background = "#c4996c") %>%
  row_spec(0, background = "#747474")
```

## General information

- The Proceedings will be published in Open Access by the International Publisher CRC Press / Balkema and will be sent to indexing services such as Scopus, WoS/Clarivate, EI, and Compendex.
- Each paper needs the registration of at least one author.
- Abstracts should have 150 to 250 words.
- Full papers should not exceed 8 pages.
- Authors of approved Abstracts should submit the final paper using the available template.
- The Open Access files will be available in the ISSMGE Online Library. The Authors will be free to upload or share the PDF content anywhere.
- After review and acceptance of the papers, the first Author of each paper will be asked to sign a "Consent to Publish" which will allow its inclusion in the Proceedings under the specified registration conditions.

## Procedure for submission of abstracts and papers to ICBBG2025 and their review process

- Abstracts are submitted to the ISSMGE platform (deadline: October 31, 2023).
- Members of an International Review Committee analyse and accept (or reject) the abstracts.
- Abstracts' status may be "pending" in the ISSMGE platform until December 15, 2023 (deadline for abstract notification acceptance).
- The Authors of accepted abstracts submit their papers using the available template (deadline: May 31, 2024).
- The Organizing Committee will send each paper for review (deadline for all reviews: July 31, 2024).
- The Authors will be informed of the result of the review process by August 15, 2024. Authors should submit the revised paper until December 15, 2024. 

## Questions?

Please send email to the organizing committee, <icbbg2015@gmail.com>
