---
title: "Call for Session Proposals"
date: "2023-04-30"
---

This is an invitation to submit proposals for sessions in the International Conference on Bio-mediated and Bio-inspired Geotechnics (ICBBG) 2025, to be held May 19-21, 2025 in Tempe, Arizona, USA.
ICBBG aims to bring together top researchers from around the world to present the state of the art and state of the practice on biogeotechnics, and to facilitate knowledge exchange among researchers, industry, agencies and educators.

A proposal should identify a coherent topic that can be addressed by about 6 to 12 papers.
For example, a session might bring together papers on different aspects to a particular biogeotechnics question (e.g., MICP, EICP, bio-inspired burrowing, root-inspired-foundation) or it might examine the applications of a particular technology (e.g., x-ray CT) in a variety of biogeotechnics areas.

ICBBG is interested in the following general themes: 

* Bio-mediated methods for hazard mitigation (e.g., liquefaction, erosion, landslides, fugitive dust)
* Bio-mediated methods for environmental protection and restoration (e.g., contaminant removal, bio-based barriers)
* Bio-mediated or bio-inspired methods for infrastructure construction (e.g., foundation systems, construction materials, intelligent and adaptive construction)
* Bio-inspired methods for subsurface exploration and excavation (e.g., probes, burrowing/excavation robots, sensing and communication systems)
* Advanced methods for biogeotechnics research (e.g., experimental, computational, biological)
* Field application of biogeotechnics 
* Education and outreach in biogeotechnics
* Any other topics related to biogeotechnics

## Responsibilities of a session chair:

Recognizing that many in the community believe the value of a meeting depends on the quality of its review process, every full manuscript submitted to ICBBG will be reviewed by at least two anonymous reviewers, as well as the session chairs. 

As a proposer of an accepted session, you will become the session chair.
The chair's primary responsibility is to solicit high quality papers for the session and to oversee the review.
You are to solicit manuscripts, have them refereed, collaborate with the conference chairs in determining which manuscripts are to be accepted and structure presentation time in your session. Please contact us at the address below if you have any questions about the obligations entailed in becoming a session organizer.

## Procedure for submitting proposals:

Session proposals can be as short as a single page, including the following information: 

* Session Title 
* Names and contact information of the organizer(s)
* Abstract (1 paragraph), describing the specific scope, purpose and significance of the session
* Rough estimate of the anticipated number of presentations
* List of potential contributors (Optional but highly recommended)

Proposals must be submitted to the email address <icbbg2025@gmail.com>.

Each proposal will be evaluated by the organizing committee.

## Important Dates

April 30, 2023 -- Proposals Due

May 31, 2023 -- Notification of Acceptance 

## Questions?

Please send email to the organizing committee, <icbbg2015@gmail.com>
