project:
  type: website
  output-dir: docs
  preview:
    port: 2025

website:
  page-footer: 
    left: Coyright © 2025 ICBBG
    center: "[Contact Us](/about.qmd)"
  google-analytics: G-12S45SR1D0
  favicon: "./img/icbbg.svg"
  navbar:
    background: primary
    logo: ./img/icbbg-logo.svg
    pinned: TRUE
    
    right:
      - href: index.qmd
        text: Home
      - importantdates.qmd
      - speakers.qmd
      - submissions.qmd
      - program.qmd
      - exhibition-sponsorship.qmd
      - venue.qmd
      - registration.qmd 
      - committees.qmd
  sidebar:
    style: "floating"
    search: true
    contents:
      section: "Opportunities"
      contents:
        - href: ./submissions/call-for-posters.qmd
          text: Call for posters
        - href: call-for-exhibitors-sponsors.qmd
          text: Call for Exhibition and Sponsorship
        - href: registration.qmd
          text: Register
  announcement:
    icon: info-circle-fill
    dismissable: true
    content: "**Register by March 15 to save with the early-bird rate!** [Learn More](/registration.qmd)"
    type: danger
    position: below-navbar
format:
  html:
    theme: 
      - ./assets/theme/cbbg.scss
    css:
      - ./assets/theme/styles.css
    toc: true
    email-obfuscation: javascript
    # include-in-header: 
    #   - assets/theme/banner.html
    filters: 
      - ./assets/theme/highlight-span.lua
execute:
  echo: false
  freeze: auto
  warning: false
  error: false
