---
title: "Committees"
subtitle: "Last Modified: 2024-12-18" 
---

## Conference Chairs

|                |                                 |         |
|----------------|---------------------------------|---------|
| Edward Kavazanjian | Arizona State University        | USA     |
| Susan Burns    | Georgia Institute of Technology | USA     |

: {tbl-colwidths="[50, 70, 20]" .hover}

## Steering Committee

|                            |                                   |             |
|----------------------------|-----------------------------------|-------------|
| Paola Bandini              | New Mexico State University       | USA         |
| Jian Chu                   | Nanyang Technological University  | Singapore   |
| Jason DeJong               | University of California, Davis   | USA         |
| Richard Fragaszy           | Program Director (Retired) at NSF | USA         |
| David Frost                | Georgia Institute of Technology   | USA         |
| Leon van Paassen           | Boskalis                          | Netherlands |
| Gioacchino (Cino) Viggiani | Université Grenoble Alpes         | France      |

: {tbl-colwidths="[50, 70, 20]" .hover}

## Organizing Committee 

|                       |                                  |           |
|-----------------------|----------------------------------|-----------|
| Julian Tao            | Arizona State University         | USA       |
| Douglas Cortes        | New Mexico State University      | USA       |
| Sheng Dai             | Georgia Institute of Technology  | USA       |
| Anca Delgado          | Arizona State University         | USA       |
| Mike Gomez            | University of Washington         | USA       |
| Satoru Kawasaki       | Hokkaido University              | Japan     |
| Joan M. Larrahondo    | Pontificia Universidad Javeriana | Colombia  |
| Thomas Lin            | Louisiana State University       | USA       |
| Alejandro Martinez    | University of California, Davis  | USA       |
| Brian Martinez        | Geosyntec Consultants            | USA       |
| Brina Montoya         | North Carolina State University  | USA       |
| Grainne El Mountassir | University of Strathclyde        | UK        |
| Md. Mizanur Rahman    | University of South Australia    | Australia |
| Yang Xiao             | Chongqing University             | China     |

: {tbl-colwidths="[50, 70, 20]" .hover}

## Local Organizing Committee

|                           |                          |                              |
|---------------------------|--------------------------|------------------------------|
| Claudia Zapata            | Arizona State University | Professor                    |
| Hamed Khodadadi Tirkolaei | Arizona State University | Assistant Professor          |
| Emmanuel Salifu           | Arizona State University | Assistant Professor          |
| Nariman Mahabadi          | Arizona State University | Assistant Professor          |
| Jean Larson               | Arizona State University | Research Associate Professor |
| Dawn Takeuchi             | Arizona State University | Staff                        |
| Emma Buchanan             | Arizona State University | Staff                        |

: {tbl-colwidths="[50, 50, 40]" .hover}

## Editorial Board

|                  |                                 |             |
|------------------|---------------------------------|-------------|
| Julian Tao       | Arizona State University        | USA         |
| Douglas Cortes   | New Mexico State University     | USA         |
| Sheng Dai        | Georgia Institute of Technology | USA         |
| Alejandro Martinez    | University of California, Davis  | USA       |
| Leon van Paassen | Boskalis                        | Netherlands |
| Mike Gomez       | University of Washington        | USA         |

: {tbl-colwidths="[50, 70, 20]" .hover}
