---
title: Registration
---

## Categories and Rates

<!-- [Register Now](https://specialevents.asu.edu/icbbg2025){.btn .btn-primary .large} -->
[Register Now](./comingsoon.qmd){.btn .btn-primary .large}

| Category        | Prior to 03/15/2025 | Full Price till 05/04/2025 |
|-----------------|---------------------|----------------------------|
| General         | $750                | $850                       |
| Student         | $400                | $400                       |
| Guest/Companion | $250                | $250                       |

[Book a room at the ICBBG 2025 Rate by Monday, April 21, 2025](https://www.marriott.com/event-reservations/reservation-link.mi?id=1733422779793&key=GRP&guestreslink2=true&app=resvlink){.btn .btn-secondary .large}

## Terms and Conditions for Conference Registration

- **Registration Includes:**

    - **Full Registration:** Reception on May 18, banquet on May 20, lunch and coffee breaks on May 19 and 20, and access to all technical programs.
    - **Guest/Companion Registration:** Reception on May 18 and banquet on May 20.
    - **Payment Deadline:** Payments must be received and processed by **May 4**; unpaid registrations will be canceled.

- **Paper Submission:**

    - At least one author of an accepted paper must complete a **full registration** for the paper to be included in the program and proceedings.
    - A maximum of **two papers** can be associated with a single registration.

- **No-shows:**

    - Registrants who do not attend the conference and fail to cancel in advance will not receive a refund.

- **Data Protection:**

    - Personal information collected during registration will only be used for conference-related purposes and will not be shared without consent.

By completing the registration process, you agree to these terms and conditions. For inquiries, please contact [icbbg2025@gmail.com](mailto:icbbg2025@gmail.com).

## Cancellation Policy

- All cancellation requests must be submitted in writing to **icbbg2025@gmail.com**.  
- **Full Refund:** Cancellations requested on or before **April 4, 2025**, will receive a 100% refund, minus a credit card processing fee.  
- **Partial Refund or Transfer:** Cancellations requested between **April 5, 2025**, and **May 2, 2025**, will receive a 50% refund, or you may transfer your registration to another attendee.  
- **No Refunds:** Cancellations after **May 2, 2025**, are not eligible for a refund; however, registration transfers to another attendee are still allowed.  


| Request Date               | Refund Amount                       | Additional Option                         |
|----------------------------|-------------------------------------|-------------------------------------------|
| On or before <br/> April 4, 2025 | 100% refund (minus credit card fee) | N/A                                       |
| April 5 – May 2, 2025      | 50% refund                          | Transfer registration to another attendee |
| After May 2, 2025          | No refund                           | Transfer registration to another attendee |

: {tbl-colwidths="[1.3, 1, 1.5]"}

For questions or to request a cancellation, please contact us at [icbbg2025@gmail.com](mailto:icbbg2025@gmail.com).

<!-- [Register Now](https://specialevents.asu.edu/icbbg2025){.btn .btn-primary .large} -->
[Register Now](./comingsoon.qmd){.btn .btn-primary .large}
[Book a room at the ICBBG 2025 Rate by Monday, April 21, 2025](https://www.marriott.com/event-reservations/reservation-link.mi?id=1733422779793&key=GRP&guestreslink2=true&app=resvlink){.btn .btn-secondary .large}
