---
title: Schedule
---

::: {.callout-note}
This is a tentative schedule and subject to change. 
:::



## Day 1

|               |                      |
|---------------|----------------------|
| 9:00 – 17:00  | workshops            |
| 18:00 – 20:00 | Icebreaker reception |


## Day 2

+ **6 keynotes + 36 paper presentations**


|       |                             |            |            |
| ----- | --------------------------- | ---        | ---        |
| 8:00  | opening & registration      |
| 8:30  | plenary session 1           |
|       | 3 x 30 minute presentation  |
| 10:00 | coffee break                |            |            |
| 10:30 | session 2a                  | session 2b | session 2c |
|       | 6 x 15 min                  | 6 x 15 min | 6 x 15 min |
| 12:00 | lunchbreak + poster session |
| 13:30 | session 3a                  | session 3b | session 3c |
|       | 6 x 15 min                  | 6 x 15 min | 6 x 15 min |
| 15:00 | coffee break                |
| 15:30 | plenary session 4           |
|       | 3 x 30 minute presentation  |
| 17:00 | end of sessions             |
| 18:00 | conference dinner           |
| 20:00 | end of day 1                |



## Day 3

+ **6 keynotes/debates + 36 paper presentations**

| 8:00  | opening & registration      |            |            |
| ----- | --------------------------- |--|--|
| 8:30  | plenary session 5           |
|       | 3 x 30 min                  |
| 10:00 | coffee break                |            |            |
| 10:30 | session 6a                  | session 6b | session 6c |
|       | 6 x 15 min                  | 6 x 15 min | 6 x 15 min |
| 12:00 | lunchbreak + poster session |
| 13:30 | session 7a                  | session 7b | session 7c |
|       | 6 x 15 min                  | 6 x 15 min | 6 x 15 min |
| 15:00 | coffee break                |
| 15:30 | plenary session 8           |
|       | 3 x 30 min                  |
| 17:00 | end of conference           |

## Day 4

* **Field trips**


::: {.content-visible when-profile="local"}

::: {.callout-note}

* Based on this original plan, there will be 12 plenary talks, 72 presentations in parallel sessions, and a number of poster presentations in 2 poster sessions.

* We may want to reduce the number of plenary talks to make room for more parallel sessions. 

* We can have at least three tracks:
  * Bio-mediated Geotechnics
  * Bio-inspired Geotechnics
  * Education, training, industrial collaboration, sustainability in Biogeotechnics

* For each track, we can have a few sessions targeting on different applications such as:
  * Bio-mediated
    * Hazard mitigation
    * Construction
    * Environmental remediation or restoration
  * Bio-inspired
    * Site investigation
    * Foundation
    * Cross-cutting
  * ETCS (successes and pitfalls)
    * Education
    * Training
    * Industrial collaborations
    * Sustainability

:::
:::

