---
title: "**Call for Abstracts**"
date: "2023-11-07"
published-title: "Last Modified"
subtitle: "Now Due: 2024-03-15"
---


[Submit an abstract](https://www.issmge.org/publications/review-platform/conferences/icbbg2025/submit-abstract){.btn .btn-primary}

We sincerely invite you to submit abstracts to the International Conference on Bio-mediated and Bio-inspired Geotechnics (ICBBG) 2025, scheduled to take place in Temple, Arizona, USA from May 19 to 21, 2025. 
ICBBG aims to bring together top researchers from around the world to present the state of the art and state of the practice on biogeotechnics, and to facilitate knowledge exchange among researchers, industry, agencies and educators.

## Themes

We call for submissions to 8 general sessions and 8 special symposia:

```{r} 
library(kableExtra)
library(tidyverse)

themes <- tribble(
  ~"General sessions", ~"Special symposia",
"Bio-mediated methods for hazard mitigation                        ", "Bio-inspired Tunneling                         ",
"Bio-mediated methods for environmental protection and restoration ", "Asia experiences on bio-mediated geotechnics   ",
"Bio-mediated methods for infrastructure construction              ", "Europe experiences on bio-mediated geotechnics ",
"Bio-inspired methods for infrastructure construction              ", "Biopolymer treated soils                       ",
"Bio-inspired methods for subsurface exploration and excavation    ", "Delivery strategies for MICP                   ",
"Fundamental research on biogeotechnics                            ", "MICP for sustainable geoenergy applications    ",
"Case studies on field applications of biogeotechnics              ", "Fungal treatment of soils                      ",
"Education, outreach, diversity, inclusion and equity in engineering", "Build with nature                              ",
) 
kbl(themes) %>%
  column_spec(1, background = "#c4996c") %>%
  row_spec(0, background = "#747474")
```

## Abstract Submission Instructions for Authors

- Abstracts should have 150 to 250 words.
- Abstracts are submitted to the [ISSMGE conference review platform](https://www.issmge.org/publications/review-platform/conferences/icbbg2025/submit-abstract) (deadline: March 15, 2024).
  - You need to use your free ISSMGE account to login
  - If you are submitting multiple papers, please use a same account
- Select a general session or a special symposium (see the above table)
  - If none of the provided themes fit your paper, please select "General session: Other"
  - Note that abstracts submitted to Special Symposia may be later reassigned to General sessions depending on the number of abstracts received for each symposium.
- Select a presentation type (oral, poster or either)

## What to Expect after Submission of Abstracts

::: {.table-striped}

| Actions                      |                                              Date |
|------------------------------|--------------------------------------------------:|
| Abstracts Due                |     ~~October 2023~~ [March 15, 2024]{.highlight} |
| Full Paper Invitations Begin |   ~~December 2023~~ [April 15, 2024 ]{.highlight} |
| Draft Papers due             |        ~~May 2024~~ [August 31, 2024]{.highlight} |
| Review Comments to Authors   |                   [November 15, 2024]{.highlight} |
| Final Papers due             | ~~December 2024~~ [January 31 , 2025]{.highlight} |
| Conference Registration Due  |                                    March 31, 2025 |

:::

## Publication and Copyright Information

- Authors retain all rights to their articles in the conference proceedings.
- A copyright agreement form will be provided to authors and must be submitted at the time of acceptance and final submission of revised papers.
- Accepted papers will be published in a free and open access conference proceedings in the ISSMGE Online Library.
- Each paper will be indexed with its own individual DOI number and Conference Proceedings, with their own ISSN.
- Additional indexing options such as Scopus, WoS/Clarivate, EI, and Compendex may be sought.
- The conference editorial board may invite selected conference papers for special issues of high impact journals.

## Questions?

Please send emails to the organizing committee, <icbbg2025@gmail.com>

To learn more, visit the conference website: <https://www.icbbg2025.com>

[Submit an abstract](https://www.issmge.org/publications/review-platform/conferences/icbbg2025/submit-abstract){.btn .btn-primary}
